export const techStacks = {
    frontend: [
        'React',
        'Next.js',
        'Remix',
        'Tailwind CSS',
        'TypeScript',
        'JavaScript',
        'Redux',
        'Shadcn',
        'Framer-Motion',
        'GSAP',
    ],
    backend: [
        'Node.js',
        'Express.js',
        'FastAPI',
        'Uvicorn',
        'REST API',
        'GraphQL',
    ],
    'db & Services': [
        'MongoDB',
        'PostgreSQL',
        'Redis',
        'GCP',
        'Docker',
        'Supabase',
        'Prisma ORM',
        'Drizzle ORM',
        'Appwrite',
        'Firebase',
        'Cloudinary',
    ],
    cybersecurity: [
        'Reconnaissance',
        'Scanning',
        'Covering Tracks',
        'Cryptography',
        'Security Protocols',
        'Network Security',
        'Web Application Security',
        // 'Penetration Testing',
        // 'Incident Response',
        // 'Digital Forensics',
        // 'Malware Analysis',
        // 'Reverse Engineering',
        // 'Threat Hunting',
        'Vulnerability Assessment',
        // 'Security Auditing',
        // 'Risk Management',
        // 'Compliance',
        // 'Security Operations Center (SOC)',
        // 'Advanced Persistent Threats (APT)',
        // 'Zero-Day Exploits'
    ],
    currentLearning: [
        'Browser Automation',
        'AI',
        'Machine Learning',
        'Cloud Architecture',
    ],
}