export const techStacks = {
    languages: [
        'C++',
        'Java',
        'JavaScript',
        'HTML/CSS',
        'Python',
        'Solidity',
    ],
    'cloud & devops': [
        'Docker',
        'Kubernetes',
        'AWS',
        'CI/CD pipelines',
        'Terraform',
        'Git',
    ],
    'networking & security': [
        'DNS/DHCP configuration',
        'Wireshark',
        'Cisco Packet Tracer',
        'Linux',
        'Snort IDS',
        'Firewall routing',
    ],
    'databases & other': [
        'MongoDB',
        'MySQL',
        'DSA',
        'OOP',
        'Database Systems',
        'Operating Systems',
    ],
    'frameworks & tools': [
        'React.js',
        'Node.js',
        'Tailwind CSS',
        'Next.js',
        'TypeScript',
        'REST APIs',
    ],
    currentLearning: [
        'Blockchain Development',
        'Machine Learning',
        'Cybersecurity',
        'Microcontroller Programming',
    ],
}